@startuml
'https://plantuml.com/class-diagram

class ChessBoard
{
    - TILES : JPanel[][] {readOnly}
    - observer : IViewObserver
    - leapedWhitePieces : JPanel
    - leapedBlackPieces : JPanel
    + <<Create>> ChessBoard(game : Game)

}

class MainMenu
{
}

interface IViewObserver
{
}

ChessBoard *--> "implements" IViewObserver


@enduml