@startuml
'https://plantuml.com/class-diagram

interface IViewObserver {
    + tileClicked(posX : int, posY : int)
    + upgradePawn(type : String, color : Color, x : int, y : int)
}

class GameController {
    - game : Game
    - view : ChessBoard
    + <<Create>> GameController(whitePlayerName : String, blackPlayerName : String)
}

GameController *--> "implements" IViewObserver

@enduml